title: "TIL With Me"
description: "Design, build, and deploy a Golang/Swift iOS app live, with me!"

# Theme configuration
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Site layout
collections:
  parts:
    output: true
    permalink: /:collection/:title

defaults:
    - scope:
        path: ""
        type: "parts"
      values:
        layout: "post"